{{ if .Values.secret.config }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "packet-cloud-config" }}
  namespace: kube-system
stringData:
  cloud-sa.json: |
    {
    "apiKey": "{{ .Values.secret.config.apiKey }}",
    "projectID": "{{ .Values.secret.config.projectID }}"
    "facilityID": "{{ .Values.secret.config.facilityID }}"
    }
{{ end }}
